import { Program, Project, News, TeamMember, Partner, Cluster } from '../types';

export const fallbackSettings: Record<string, string> = {
  founded_year: '2019',
  experience_years: '7',
  active_projects: '10',
  provinces_count: '12',
  beneficiaries: '50000',
  address: 'Kinshasa Songololo 145',
};

export const fallbackPrograms: Program[] = [
  {
    id: 'p1',
    title: 'Autonomisation économique',
    slug: 'autonomisation-economique',
    description: "Renforcer l'indépendance financière des femmes à travers la formation professionnelle et l'entrepreneuriat.",
    long_description: "Ce programme vise à émanciper les femmes économiquement en leur offrant des formations professionnelles, un accès au micro-crédit et un accompagnement dans la création d'entreprises.",
    icon: 'trending-up',
    color: 'sky',
    order: 1,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p2',
    title: 'Lutte contre les violences basées sur le genre (VBG/PSA/HS)',
    slug: 'lutte-violences-genre',
    description: 'Prévenir et répondre aux violences sexuelles, psychosociales et basées sur le genre faites aux femmes et aux filles.',
    long_description: 'Ce programme coordonne la réponse aux VBG à travers des centres d\'écoute, une assistance juridique et psychologique et des campagnes de sensibilisation communautaire.',
    icon: 'shield',
    color: 'red',
    order: 2,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p3',
    title: 'Santé maternelle et infantile',
    slug: 'sante-maternelle-infantile',
    description: "Améliorer l'accès aux soins de santé pour les mères et les enfants.",
    long_description: "Ce programme améliore la santé reproductive, maternelle et infantile via des cliniques mobiles, la formation des accoucheuses et la sensibilisation aux soins prénataux.",
    icon: 'heart',
    color: 'pink',
    order: 3,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p4',
    title: 'Éducation et alphabétisation',
    slug: 'education-alphabetisation',
    description: "Promouvoir l'accès à l'éducation pour les femmes et les filles.",
    long_description: "Ce programme soutient la scolarisation des filles, l'alphabétisation des femmes adultes et la formation des enseignants dans les zones reculées.",
    icon: 'book-open',
    color: 'blue',
    order: 4,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p5',
    title: 'WASH - Eau, Hygiène et Assainissement',
    slug: 'wash',
    description: "Assurer l'accès à l'eau potable et aux installations sanitaires dans les communautés.",
    long_description: "Ce programme construit des points d'eau, des latrines et forme les communautés aux bonnes pratiques d'hygiène pour réduire les maladies liées à l'eau.",
    icon: 'droplet',
    color: 'cyan',
    order: 5,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p6',
    title: "Réponse humanitaire d'urgence",
    slug: 'reponse-humanitaire',
    description: "Apporter une aide d'urgence aux populations déplacées et affectées par les conflits.",
    long_description: "Ce programme assure une réponse rapide aux crises humanitaires à travers la distribution de kits d'urgence, d'abris et de nourriture aux populations déplacées.",
    icon: 'alert-triangle',
    color: 'orange',
    order: 6,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p7',
    title: 'Plaidoyer et droits des femmes',
    slug: 'plaidoyer-droits-femmes',
    description: 'Défendre les droits des femmes et influencer les politiques publiques.',
    long_description: "Ce programme plaide pour l'adoption de lois protectrices des droits des femmes, la participation des femmes en politique et la lutte contre les discriminations de genre.",
    icon: 'megaphone',
    color: 'green',
    order: 7,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'p8',
    title: 'Préparation et réponse aux urgences sanitaires',
    slug: 'urgences-sanitaires',
    description: 'Préparer et répondre aux épidémies et pandémies affectant les communautés vulnérables.',
    long_description: "Ce programme renforce la capacité de préparation et de réponse rapide aux urgences sanitaires incluant les épidémies (Ebola, choléra, rougeole, mpox) et pandémies.",
    icon: 'activity',
    color: 'red',
    order: 8,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const fallbackProjects: Project[] = [
  {
    id: 'proj1',
    program_id: 'p1',
    title: 'Formation en entrepreneuriat féminin à Kinshasa',
    slug: 'formation-entrepreneuriat-kinshasa',
    description: 'Formation de 200 femmes aux techniques entrepreneuriales et gestion financière.',
    location: 'Kinshasa',
    status: 'en_cours',
    start_date: '2024-01-15',
    beneficiaries: 200,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj2',
    program_id: 'p3',
    title: 'Cliniques mobiles au Kasaï',
    slug: 'cliniques-mobiles-kasai',
    description: 'Déploiement de cliniques mobiles pour les soins maternels et infantiles dans les zones reculées.',
    location: 'Kasaï Oriental',
    status: 'en_cours',
    start_date: '2023-06-01',
    beneficiaries: 5000,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj3',
    program_id: 'p4',
    title: 'Alphabétisation des femmes rurales au Maniema',
    slug: 'alphabetisation-maniema',
    description: "Programme d'alphabétisation pour les femmes de 18 à 45 ans en milieu rural au Maniema.",
    location: 'Maniema',
    status: 'en_cours',
    start_date: '2024-03-01',
    beneficiaries: 350,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj4',
    program_id: 'p5',
    title: 'Construction de puits et latrines au Nord-Kivu',
    slug: 'puits-latrines-nord-kivu',
    description: 'Construction de 20 puits et 50 blocs de latrines dans les camps de déplacés du Nord-Kivu.',
    location: 'Nord-Kivu',
    status: 'en_cours',
    start_date: '2024-02-01',
    beneficiaries: 8000,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj5',
    program_id: 'p6',
    title: "Aide d'urgence aux déplacés de l'Ituri",
    slug: 'aide-urgence-ituri',
    description: "Distribution de kits alimentaires et d'hygiène à 3000 familles déplacées en Ituri.",
    location: 'Ituri',
    status: 'en_cours',
    start_date: '2024-07-01',
    beneficiaries: 15000,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj6',
    program_id: 'p2',
    title: "Centre d'écoute VBG à Kinshasa",
    slug: 'centre-ecoute-vbg-kinshasa',
    description: "Création d'un centre d'écoute et d'assistance juridique pour les survivantes de VBG.",
    location: 'Kinshasa',
    status: 'en_cours',
    start_date: '2023-03-01',
    beneficiaries: 1200,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj7',
    program_id: 'p5',
    title: "Accès à l'eau potable au Sud-Kivu",
    slug: 'eau-potable-sud-kivu',
    description: "Installation de systèmes de captage d'eau de source pour 10 villages au Sud-Kivu.",
    location: 'Sud-Kivu',
    status: 'en_cours',
    start_date: '2024-05-01',
    beneficiaries: 6500,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj8',
    program_id: 'p3',
    title: 'Maternités sécurisées en Tshopo',
    slug: 'maternites-securisees-tshopo',
    description: 'Réhabilitation de 4 maternités et formation de sages-femmes pour réduire la mortalité maternelle.',
    location: 'Tshopo',
    status: 'en_cours',
    start_date: '2023-10-01',
    beneficiaries: 3500,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj9',
    program_id: 'p4',
    title: 'École pour filles déplacées à Goma',
    slug: 'ecole-filles-deplacees-goma',
    description: "Création d'espaces temporaires d'apprentissage pour 400 filles déplacées à Goma.",
    location: 'Goma, Nord-Kivu',
    status: 'termine',
    start_date: '2022-01-15',
    beneficiaries: 400,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'proj10',
    program_id: 'p1',
    title: 'Coopératives féminines au Tanganyika',
    slug: 'cooperatives-feminines-tanganyika',
    description: 'Création et accompagnement de 10 coopératives féminines productrices de manioc et arachide.',
    location: 'Tanganyika',
    status: 'en_cours',
    start_date: '2024-09-01',
    beneficiaries: 250,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const fallbackTeam: TeamMember[] = [
  {
    id: 't1',
    name: 'Marie Kabamba',
    role: 'Présidente',
    description: "Leader visionnaire avec 20 ans d'expérience dans le développement communautaire et la défense des droits des femmes.",
    gender: 'femme',
    order: 1,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't2',
    name: 'Jeanne Mukendi',
    role: 'Directrice Exécutive',
    description: 'Experte en gestion de projets humanitaires et développement durable en contexte de crise.',
    gender: 'femme',
    order: 2,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't3',
    name: 'Grace Tshilombo',
    role: 'Coordinatrice des Programmes',
    description: 'Spécialiste en santé maternelle et infantile avec 12 ans d\'expérience terrain.',
    gender: 'femme',
    order: 3,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't4',
    name: 'Espérance Nsimba',
    role: 'Responsable Communication',
    description: "Journaliste et militante pour les droits des femmes et l'égalité des genres.",
    gender: 'femme',
    order: 4,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't5',
    name: 'Patience Kalala',
    role: 'Coordinatrice VBG/PSA/HS',
    description: 'Experte en protection et réponse aux violences basées sur le genre dans les zones de conflit.',
    gender: 'femme',
    order: 5,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't6',
    name: 'Claudine Mwanza',
    role: 'Responsable Finances',
    description: 'Comptable certifiée avec expertise en gestion financière des ONG humanitaires.',
    gender: 'femme',
    order: 6,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't7',
    name: 'Yvette Bolamba',
    role: 'Coordinatrice WASH',
    description: 'Ingénieure sanitaire spécialisée dans les projets eau, hygiène et assainissement.',
    gender: 'femme',
    order: 7,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't8',
    name: 'Solange Luboya',
    role: 'Responsable Plaidoyer',
    description: "Avocate engagée dans la défense des droits des femmes et des enfants en RDC.",
    gender: 'femme',
    order: 8,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't9',
    name: 'Jean-Paul Lukusa',
    role: 'Responsable Logistique',
    description: 'Expert logistique avec expérience dans les opérations humanitaires en zones reculées.',
    gender: 'homme',
    order: 9,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 't10',
    name: 'Pierre Mbuyi',
    role: 'Responsable IT',
    description: "Ingénieur informatique assurant la transformation numérique de l'organisation.",
    gender: 'homme',
    order: 10,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const fallbackPartners: Partner[] = [
  { id: 'part1', name: 'UNICEF', category: 'international', order: 1, active: true, created_at: new Date().toISOString() },
  { id: 'part2', name: 'ONU Femmes', category: 'international', order: 2, active: true, created_at: new Date().toISOString() },
  { id: 'part3', name: 'USAID', category: 'international', order: 3, active: true, created_at: new Date().toISOString() },
  { id: 'part4', name: 'Union Européenne', category: 'international', order: 4, active: true, created_at: new Date().toISOString() },
  { id: 'part5', name: 'OMS', category: 'international', order: 5, active: true, created_at: new Date().toISOString() },
  { id: 'part6', name: 'UNHCR', category: 'international', order: 6, active: true, created_at: new Date().toISOString() },
  { id: 'part7', name: 'Gouvernement RDC', category: 'gouvernement', order: 7, active: true, created_at: new Date().toISOString() },
  { id: 'part8', name: 'Centre Carter', category: 'ong', order: 8, active: true, created_at: new Date().toISOString() },
  { id: 'part9', name: 'Expertise France', category: 'international', order: 9, active: true, created_at: new Date().toISOString() }
];

export const fallbackNews: News[] = [
  {
    id: 'n1',
    title: "L'AFD renforce ses actions contre les VBG dans l'Est du Congo",
    slug: 'afd-actions-vbg-est-congo',
    excerpt: "L'AFD intensifie ses interventions de protection et d'assistance aux survivantes de violences basées sur le genre dans les provinces de l'Est.",
    content: "Dans le cadre du cluster Protection, l'Alliance des Femmes pour le Développement (AFD) renforce ses équipes de réponse aux VBG dans les provinces du Nord-Kivu, Sud-Kivu et de l'Ituri, où les violences contre les femmes restent alarmantes en raison des conflits armés persistants.",
    category: 'article',
    published: true,
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    author: 'AFD',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'n2',
    title: 'Lancement du programme de formation entrepreneurial à Kinshasa',
    slug: 'lancement-formation-entrepreneuriale-kinshasa',
    excerpt: "Plus de 200 femmes bénéficient d'une formation intensive en entrepreneuriat et gestion financière dans la capitale.",
    content: "L'Alliance des Femmes pour le Développement a officiellement lancé son nouveau programme de formation en entrepreneuriat féminin à Kinshasa. Ce programme, financé par l'Union Européenne, accompagnera 200 femmes sur 24 mois.",
    category: 'article',
    published: true,
    published_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    author: 'AFD',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'n3',
    title: 'AFD participe au Forum Humanitaire de Genève',
    slug: 'afd-forum-humanitaire-geneve',
    excerpt: "Une délégation de l'AFD représente la société civile congolaise au Forum Humanitaire Mondial de Genève.",
    content: "La présidente de l'AFD, Marie Kabamba, a représenté l'organisation au Forum Humanitaire Mondial à Genève, plaidant pour un renforcement du financement de la réponse humanitaire en RDC.",
    category: 'article',
    published: true,
    published_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    author: 'AFD',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const fallbackClusters: Cluster[] = [
  { id: 'c1', name: 'Cluster Protection', type: 'cluster', description: "Coordination des interventions de protection des civils, des femmes et des enfants dans les zones de crise.", icon: 'shield', order: 1, active: true, created_at: new Date().toISOString() },
  { id: 'c2', name: 'Cluster Santé', type: 'cluster', description: "Coordination des services de santé d'urgence, y compris la santé reproductive et maternelle.", icon: 'heart-pulse', order: 2, active: true, created_at: new Date().toISOString() },
  { id: 'c3', name: 'Cluster Éducation', type: 'cluster', description: "Coordination des activités d'éducation en situations d'urgence et de maintien de la scolarisation.", icon: 'book-open', order: 3, active: true, created_at: new Date().toISOString() },
  { id: 'c4', name: 'Cluster WASH', type: 'cluster', description: "Coordination des interventions eau, hygiène et assainissement dans les zones affectées.", icon: 'droplet', order: 4, active: true, created_at: new Date().toISOString() },
  { id: 'c5', name: 'Cluster Nutrition', type: 'cluster', description: "Coordination de la réponse nutritionnelle pour lutter contre la malnutrition aiguë sévère.", icon: 'apple', order: 5, active: true, created_at: new Date().toISOString() },
  { id: 'c6', name: 'GT Santé Sexuelle et Reproductive (SSR)', type: 'working_group', description: "Groupe de travail assurant l'accès aux soins de santé sexuelle et reproductive en situation d'urgence.", icon: 'activity', order: 6, active: true, created_at: new Date().toISOString() },
  { id: 'c7', name: 'GT Violences Basées sur le Genre (VBG)', type: 'working_group', description: "Groupe de travail coordonnant la prévention et la réponse aux violences basées sur le genre.", icon: 'shield-alert', order: 7, active: true, created_at: new Date().toISOString() },
  { id: 'c8', name: 'GT Logistique', type: 'working_group', description: "Groupe de travail assurant la coordination logistique pour la livraison de l'aide humanitaire.", icon: 'truck', order: 8, active: true, created_at: new Date().toISOString() },
];
