export const DOCUMENT_TYPE_OPTIONS = [
  // Finance
  { value: "rapport_financier", label: "Rapport financier", module: "finances" },
  { value: "budget", label: "Budget", module: "budgets" },
  { value: "etat_depenses", label: "État des dépenses", module: "depenses" },
  { value: "facture", label: "Facture", module: "depenses" },
  { value: "recu", label: "Reçu", module: "depenses" },
  { value: "bon_commande", label: "Bon de commande", module: "depenses" },
  { value: "bon_paiement", label: "Bon de paiement", module: "depenses" },
  { value: "etat_caisse", label: "État de caisse", module: "finances" },
  { value: "releve_bancaire", label: "Relevé bancaire", module: "finances" },
  { value: "piece_justificative", label: "Pièce justificative", module: "depenses" },
  // Stocks
  { value: "rapport_stock", label: "Rapport de stock", module: "stocks" },
  { value: "fiche_stock", label: "Fiche de stock", module: "stocks" },
  { value: "inventaire", label: "Inventaire", module: "stocks" },
  { value: "bon_entree", label: "Bon d’entrée", module: "stocks" },
  { value: "bon_sortie", label: "Bon de sortie", module: "stocks" },
  { value: "bon_livraison", label: "Bon de livraison", module: "logistique" },
  { value: "rapport_logistique", label: "Rapport logistique", module: "logistique" },
  { value: "rapport_vehicule", label: "Rapport de véhicule", module: "logistique" },
  { value: "rapport_carburant", label: "Rapport de carburant", module: "logistique" },
  // Programmes
  { value: "rapport_mensuel", label: "Rapport mensuel", module: "rapports" },
  { value: "rapport_trimestriel", label: "Rapport trimestriel", module: "rapports" },
  { value: "rapport_annuel", label: "Rapport annuel", module: "rapports" },
  { value: "rapport_activite", label: "Rapport d’activité", module: "activites" },
  { value: "rapport_projet", label: "Rapport de projet", module: "projets" },
  { value: "rapport_mission", label: "Rapport de mission", module: "activites" },
  { value: "rapport_distribution", label: "Rapport de distribution", module: "activites" },
  { value: "rapport_formation", label: "Rapport de formation", module: "activites" },
  { value: "rapport_sensibilisation", label: "Rapport de sensibilisation", module: "activites" },
  // MEAL
  { value: "rapport_beneficiaires", label: "Rapport bénéficiaires", module: "beneficiaires" },
  { value: "rapport_indicateurs", label: "Rapport d’indicateurs", module: "indicateurs" },
  { value: "rapport_suivi", label: "Rapport de suivi", module: "indicateurs" },
  { value: "rapport_evaluation", label: "Rapport d’évaluation", module: "indicateurs" },
  { value: "rapport_enquete", label: "Rapport d’enquête", module: "indicateurs" },
  { value: "rapport_impact", label: "Rapport d’impact", module: "indicateurs" },
  // Organisation
  { value: "rapport_rh", label: "Rapport RH", module: "documents" },
  { value: "feuille_presence", label: "Feuille de présence", module: "documents" },
  { value: "rapport_partenaire", label: "Rapport partenaire", module: "documents" },
  { value: "compte_rendu", label: "Compte rendu", module: "documents" },
  { value: "proces_verbal", label: "Procès-verbal", module: "documents" },
  { value: "rapport_institutionnel", label: "Rapport institutionnel", module: "rapports" },
  { value: "autre", label: "Autre", module: "autre" },
] as const;
