import type { Permission } from "@/config/permissions";

/**
 * Permission minimale pour afficher un lien de la sidebar admin.
 * Les routes restent protégées côté serveur via requireAdmin / requirePermission.
 */
export const adminNavPermissions: Record<string, Permission | Permission[]> = {
  "/admin": "dashboard:read",
  "/admin/dashboard/donnees-mensuelles": "dashboard:read",
  "/admin/programmes": "programmes:read",
  "/admin/projets": "projets:read",
  "/admin/activites": "activites:read",
  "/admin/activites/nouvelle": "activites:write",
  "/admin/zones-intervention": "projets:read",
  "/admin/zones-intervention/nouvelle": "programmes:write",
  "/admin/urgences": "urgences:read",
  "/admin/urgences/nouvelle": "urgences:write",
  "/admin/clusters": "clusters:read",
  "/admin/stocks": "stocks:read",
  "/admin/stocks/mouvements": "stocks:read",
  "/admin/logistique": "logistique:read",
  "/admin/logistique/demandes": "logistique:read",
  "/admin/logistique/vehicules": "logistique:read",
  "/admin/logistique/missions": "logistique:read",
  "/admin/beneficiaires": "beneficiaires:read",
  "/admin/beneficiaires/nouveau": "beneficiaires:write",
  "/admin/indicateurs": "indicateurs:read",
  "/admin/resultats": "indicateurs:read",
  "/admin/enquetes": "enquetes:read",
  "/admin/enquetes/nouvelle": "enquetes:write",
  "/admin/histoires-impact": "histoires:read",
  "/admin/temoignages": "histoires:read",
  "/admin/actualites": "actualites:read",
  "/admin/publications": "actualites:read",
  "/admin/publications/archives": "archives:read",
  "/admin/bibliotheque": "archives:read",
  "/admin/bibliotheque/activites": "archives:read",
  "/admin/bibliotheque/albums": "archives:read",
  "/admin/bibliotheque/photos": "archives:read",
  "/admin/bibliotheque/videos": "archives:read",
  "/admin/bibliotheque/rapports": "archives:read",
  "/admin/bibliotheque/documents": "archives:read",
  "/admin/bibliotheque/categories": "archives:read",
  "/admin/bibliotheque/tags": "archives:read",
  "/admin/bibliotheque/archives": "archives:read",
  "/admin/bibliotheque/import": "archives:write",
  "/admin/bibliotheque/parametres": "archives:read",
  "/admin/publications/archives/nouvelle": "archives:write",
  "/admin/publications/pages": "pages:write",
  "/admin/mediatheque": "mediatheque:read",
  "/admin/newsletter": "newsletter:read",
  "/admin/newsletter/abonnes": "newsletter:read",
  "/admin/newsletter/campagnes": "newsletter:read",
  "/admin/newsletter/campagnes/nouvelle": "newsletter:write",
  "/admin/newsletter/modeles": "newsletter:read",
  "/admin/newsletter/segments": "newsletter:read",
  "/admin/newsletter/statistiques": "newsletter:read",
  "/admin/messages": "messages:read",
  "/admin/adhesions": "adhesions:read",
  "/admin/partenariats": "partenaires:read",
  "/admin/dons": "dons:read",
  "/admin/dons/intentions": "dons:read",
  "/admin/dons/transactions": "payments:read",
  "/admin/dons/remboursements": "payments:manage",
  "/admin/opportunites": "opportunites:read",
  "/admin/opportunites/nouvelle": "opportunites:write",
  "/admin/candidatures": "candidatures:read",
  "/admin/appels-offres": "appels-offres:read",
  "/admin/partenaires": "partenaires:read",
  "/admin/equipe": "equipe:read",
  "/admin/departements": "equipe:read",
  "/admin/utilisateurs": ["utilisateurs:read", "users.view"],
  "/admin/administrateur-principal": [
    "users.manage_principal",
    "users.create_super_admin",
  ],
  "/admin/administrateur-principal/creer": [
    "users.manage_principal",
    "users.create_super_admin",
  ],
  "/admin/administrateur-principal/modifier": [
    "users.manage_principal",
    "users.create_super_admin",
  ],
  "/admin/administrateur-principal/historique": [
    "users.manage_principal",
    "users.view_audit",
  ],
  "/admin/utilisateurs/nouveau": "users.invite",
  "/admin/utilisateurs/invitations": "users.invite",
  "/admin/invitations": "users.invite",
  "/admin/acces": ["users.view", "users.assign_permissions"],
  "/admin/mon-profil": "dashboard:read",
  "/admin/rh": "hr.view",
  "/admin/rh/personnel": "hr.view",
  "/admin/rh/personnel/nouveau": "hr.manage_employees",
  "/admin/rh/departements": "hr.view",
  "/admin/rh/postes": "hr.view",
  "/admin/rh/organigramme": "hr.view",
  "/admin/rh/recrutement": "hr.manage_recruitment",
  "/admin/rh/candidatures": "hr.manage_recruitment",
  "/admin/rh/presences": "hr.manage_attendance",
  "/admin/rh/horaires": "hr.manage_attendance",
  "/admin/rh/feuilles-temps": "hr.manage_attendance",
  "/admin/rh/conges": "hr.manage_leave",
  "/admin/rh/contrats": "hr.manage_contracts",
  "/admin/rh/performance": "hr.manage_performance",
  "/admin/rh/formations": "hr.manage_training",
  "/admin/rh/equipements": "hr.view",
  "/admin/rh/discipline": "hr.manage_discipline",
  "/admin/rh/reclamations": "hr.manage_discipline",
  "/admin/rh/departs": "hr.manage_offboarding",
  "/admin/rh/avances": "payroll.view",
  "/admin/rh/prets": "payroll.view",
  "/admin/rh/paie": "payroll.view",
  "/admin/rh/paie/periodes": "payroll.view",
  "/admin/rh/paie/bulletins": "payroll.view_salary",
  "/admin/rh/paie/regles": "payroll.manage_rules",
  "/admin/rh/documents": "hr_documents.view",
  "/admin/rh/onboarding": "hr.manage_recruitment",
  "/admin/rh/offboarding": "hr.manage_offboarding",
  "/admin/agents": "agents:read",
  "/admin/agents/nouveau": "agents:write",
  "/admin/finances": "finances:read",
  "/admin/finances/budgets": "finances:read",
  "/admin/finances/depenses": "finances:read",
  "/admin/finances/transactions": ["finances:read", "payments:read"],
  "/admin/rapports": "rapports:read",
  "/admin/rapports/nouveau": "rapports:write",
  "/admin/rapports/modeles": "rapports:read",
  "/admin/rapports/historique": "rapports:read",
  "/admin/documents": "documents:read",
  "/admin/documents/nouveau": "documents:write",
  "/admin/import-intelligent": "ocr.view",
  "/admin/import-intelligent/nouveau": "ocr.upload",
  "/admin/import-intelligent/missions": "ocr.upload",
  "/admin/import-intelligent/finances": "ocr.upload",
  "/admin/import-intelligent/photos": "ocr.upload",
  "/admin/import-intelligent/communications": "ocr.upload",
  "/admin/import-intelligent/beneficiaires": "ocr.upload",
  "/admin/import-intelligent/historique": "ocr.view",
  "/admin/import-intelligent/modeles": "ocr.manage_models",
  "/admin/import-intelligent/regles": "ocr.manage_rules",
  "/admin/import-intelligent/file-attente": "ocr.process",
  "/admin/parametres/demonstration": "parametres:manage",
  "/admin/exports": "rapports:export",
  "/admin/statistiques": "statistiques:read",
  "/admin/roles": "roles:manage",
  "/admin/permissions": "roles:manage",
  "/admin/parametres": "parametres:manage",
  "/admin/journal-activite": "journal:read",
  "/admin/securite": ["parametres:manage", "users.view_security"],
  "/admin/securite/sessions": ["users.view_security", "users.revoke_sessions"],
  "/admin/sauvegardes": "parametres:manage",
  "/admin/systeme": "parametres:manage",
};

export function navItemAllowed(
  href: string,
  has: (permission: Permission) => boolean,
  itemRoles?: string[],
  userRoles?: string[],
): boolean {
  if (itemRoles?.length) {
    const roles = userRoles ?? [];
    if (!itemRoles.some((r) => roles.includes(r))) return false;
  }
  const required = adminNavPermissions[href];
  if (!required) return true;
  if (Array.isArray(required)) {
    return required.some((permission) => has(permission));
  }
  return has(required);
}
