import type { Role } from "./roles";

export const permissions = [
  "dashboard:read",
  "programmes:read",
  "programmes:write",
  "projets:read",
  "projets:write",
  "activites:read",
  "activites:write",
  "beneficiaires:read",
  "beneficiaires:write",
  "indicateurs:read",
  "indicateurs:write",
  "finances:read",
  "finances:write",
  "dons:read",
  "dons:write",
  "payments:read",
  "payments:manage",
  "actualites:read",
  "actualites:write",
  "mediatheque:read",
  "mediatheque:write",
  "newsletter:read",
  "newsletter:write",
  "newsletter:send",
  "messages:read",
  "messages:write",
  "adhesions:read",
  "adhesions:write",
  "partenaires:read",
  "partenaires:write",
  "clusters:read",
  "clusters:write",
  "urgences:read",
  "urgences:write",
  "equipe:read",
  "equipe:write",
  "statistiques:read",
  "rapports:read",
  "rapports:write",
  "rapports:export",
  "opportunites:read",
  "opportunites:write",
  "candidatures:read",
  "candidatures:write",
  "documents:read",
  "documents:write",
  "histoires:read",
  "histoires:write",
  "temoignages:write",
  "appels-offres:read",
  "appels-offres:write",
  "enquetes:read",
  "enquetes:write",
  "agents:read",
  "agents:write",
  "pages:write",
  "utilisateurs:read",
  "utilisateurs:write",
  "roles:manage",
  "parametres:manage",
  "journal:read",
  "ocr.view",
  "ocr.upload",
  "ocr.process",
  "ocr.review",
  "ocr.approve",
  "ocr.apply",
  "ocr.reject",
  "ocr.manage_models",
  "ocr.manage_rules",
  "ocr.view_sensitive",
  "ocr.verify_integrity",
  "ocr.rollback_import",
  "stocks:read",
  "stocks:write",
  "logistique:read",
  "logistique:write",
  "workflows:manage",
  "jobs:manage",
  "notifications:manage",
  "users.view",
  "users.invite",
  "users.create_admin",
  "users.create_super_admin",
  "users.edit",
  "users.suspend",
  "users.disable",
  "users.archive",
  "users.assign_roles",
  "users.assign_permissions",
  "users.revoke_sessions",
  "users.view_security",
  "users.view_audit",
  "hr.view",
  "hr.view_private",
  "hr.manage_employees",
  "hr.manage_contracts",
  "hr.manage_attendance",
  "hr.manage_leave",
  "hr.manage_performance",
  "hr.manage_training",
  "hr.manage_recruitment",
  "hr.manage_discipline",
  "hr.manage_offboarding",
  "payroll.view",
  "payroll.calculate",
  "payroll.manage_components",
  "payroll.review_hr",
  "payroll.review_finance",
  "payroll.approve",
  "payroll.mark_paid",
  "payroll.close",
  "payroll.reverse",
  "payroll.view_salary",
  "payroll.export",
  "payroll.manage_rules",
  "hr_documents.view",
  "hr_documents.upload",
  "hr_documents.download",
  "hr_documents.archive",
  "hr_documents.delete",
] as const;

export type Permission = (typeof permissions)[number];

/** Matrice indicative — la vérification réelle se fera aussi via RLS Supabase et côté serveur. */
const hrPermissions = [
  "hr.view",
  "hr.view_private",
  "hr.manage_employees",
  "hr.manage_contracts",
  "hr.manage_attendance",
  "hr.manage_leave",
  "hr.manage_performance",
  "hr.manage_training",
  "hr.manage_recruitment",
  "hr.manage_offboarding",
  "hr_documents.view",
  "hr_documents.upload",
  "hr_documents.download",
  "payroll.view",
  "payroll.review_hr",
  "users.view",
  "users.invite",
] as const satisfies readonly Permission[];

const payrollFinancePermissions = [
  "payroll.view",
  "payroll.calculate",
  "payroll.manage_components",
  "payroll.review_finance",
  "payroll.approve",
  "payroll.mark_paid",
  "payroll.close",
  "payroll.view_salary",
  "payroll.export",
  "payroll.manage_rules",
] as const satisfies readonly Permission[];

export const rolePermissions: Record<Role, readonly Permission[]> = {
  platform_owner: permissions,
  platform_admin: [
    "dashboard:read",
    "journal:read",
    "users.view",
    "users.view_audit",
    "utilisateurs:read",
  ],
  support_agent: [
    "dashboard:read",
    "journal:read",
    "users.view_audit",
  ],
  billing_admin: ["dashboard:read"],
  tenant_owner: permissions,
  tenant_super_admin: permissions,
  super_admin: permissions,
  administrateur: [
    "dashboard:read",
    "utilisateurs:read",
    "utilisateurs:write",
    "users.view",
    "users.invite",
    "users.create_admin",
    "users.edit",
    "users.suspend",
    "hr.view",
    "hr.manage_employees",
    "journal:read",
    "users.view_audit",
  ],
  responsable_module: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "activites:read",
    "hr.view",
  ],
  employe: ["dashboard:read", "hr.view"],
  agent_terrain: ["dashboard:read", "agents:read", "enquetes:read"],
  auditeur: [
    "dashboard:read",
    "journal:read",
    "users.view_audit",
    "hr.view",
    "payroll.view",
    "statistiques:read",
  ],
  partenaire_lecture: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "statistiques:read",
    "rapports:read",
  ],
  utilisateur_public: [],
  direction_generale: [
    "dashboard:read",
    "programmes:read",
    "programmes:write",
    "projets:read",
    "projets:write",
    "activites:read",
    "beneficiaires:read",
    "indicateurs:read",
    "finances:read",
    "dons:read",
    "payments:read",
    "actualites:read",
    "actualites:write",
    "newsletter:read",
    "messages:read",
    "adhesions:read",
    "partenaires:read",
    "partenaires:write",
    "clusters:read",
    "urgences:read",
    "urgences:write",
    "clusters:read",
    "urgences:read",
    "urgences:write",
    "equipe:read",
    "statistiques:read",
    "rapports:read",
    "rapports:write",
    "rapports:export",
    "histoires:read",
    "histoires:write",
    "temoignages:write",
    "appels-offres:read",
    "appels-offres:write",
    "enquetes:read",
    "enquetes:write",
    "agents:read",
    "agents:write",
    "pages:write",
    "utilisateurs:read",
    "journal:read",
    "ocr.view",
    "ocr.review",
    "ocr.approve",
    "ocr.view_sensitive",
    "ocr.verify_integrity",
    "users.view",
    "hr.view",
  ],
  secretariat: [
    "dashboard:read",
    "messages:read",
    "messages:write",
    "adhesions:read",
    "adhesions:write",
    "partenaires:read",
    "equipe:read",
    "actualites:read",
  ],
  charge_programmes: [
    "dashboard:read",
    "programmes:read",
    "programmes:write",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "indicateurs:write",
    "statistiques:read",
    "rapports:read",
    "rapports:write",
    "enquetes:read",
    "enquetes:write",
    "ocr.view",
    "ocr.upload",
    "ocr.review",
    "stocks:read",
    "stocks:write",
    "logistique:read",
    "logistique:write",
    ...hrPermissions,
  ],
  coordination_urgences: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "rapports:read",
    "urgences:read",
    "urgences:write",
  ],
  coordination_sante: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "rapports:read",
  ],
  coordination_developpement: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "rapports:read",
  ],
  coordination_meal: [
    "dashboard:read",
    "indicateurs:read",
    "indicateurs:write",
    "beneficiaires:read",
    "statistiques:read",
    "rapports:read",
    "rapports:write",
    "rapports:export",
    "ocr.view",
    "ocr.review",
  ],
  logistique: [
    "dashboard:read",
    "projets:read",
    "activites:read",
    "rapports:read",
    "ocr.view",
    "ocr.upload",
    "ocr.review",
  ],
  ressources_humaines: [
    "dashboard:read",
    "equipe:read",
    "equipe:write",
    "utilisateurs:read",
    "utilisateurs:write",
    "opportunites:read",
    "opportunites:write",
    "candidatures:read",
    "candidatures:write",
    "agents:read",
    "agents:write",
    "enquetes:read",
    ...hrPermissions,
    "hr.manage_discipline",
  ],
  finance: [
    "dashboard:read",
    "finances:read",
    "finances:write",
    "dons:read",
    "dons:write",
    "payments:read",
    "payments:manage",
    "rapports:read",
    "rapports:export",
    "ocr.view",
    "ocr.upload",
    "ocr.process",
    "ocr.review",
    "ocr.approve",
    "ocr.apply",
    "ocr.reject",
    "ocr.verify_integrity",
    "ocr.view_sensitive",
    ...payrollFinancePermissions,
    "hr.view",
  ],
  communication: [
    "dashboard:read",
    "actualites:read",
    "actualites:write",
    "mediatheque:read",
    "mediatheque:write",
    "newsletter:read",
    "newsletter:write",
    "newsletter:send",
    "messages:read",
    "documents:read",
    "documents:write",
  ],
  lecture_partenaire: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "statistiques:read",
    "rapports:read",
  ],
};

export function roleHasPermission(role: Role, permission: Permission): boolean {
  return rolePermissions[role].includes(permission);
}
