import type { Role } from "./roles";

export const permissions = [
  "dashboard:read",
  "programmes:read",
  "programmes:write",
  "projets:read",
  "projets:write",
  "activites:read",
  "activites:write",
  "beneficiaires:read",
  "beneficiaires:write",
  "indicateurs:read",
  "indicateurs:write",
  "finances:read",
  "finances:write",
  "dons:read",
  "dons:write",
  "payments:read",
  "payments:manage",
  "actualites:read",
  "actualites:write",
  "mediatheque:read",
  "mediatheque:write",
  "newsletter:read",
  "newsletter:write",
  "newsletter:send",
  "messages:read",
  "messages:write",
  "adhesions:read",
  "adhesions:write",
  "partenaires:read",
  "partenaires:write",
  "clusters:read",
  "clusters:write",
  "urgences:read",
  "urgences:write",
  "equipe:read",
  "equipe:write",
  "statistiques:read",
  "rapports:read",
  "rapports:write",
  "rapports:export",
  "opportunites:read",
  "opportunites:write",
  "candidatures:read",
  "candidatures:write",
  "documents:read",
  "documents:write",
  "histoires:read",
  "histoires:write",
  "temoignages:write",
  "appels-offres:read",
  "appels-offres:write",
  "enquetes:read",
  "enquetes:write",
  "agents:read",
  "agents:write",
  "pages:write",
  "utilisateurs:read",
  "utilisateurs:write",
  "roles:manage",
  "parametres:manage",
  "journal:read",
] as const;

export type Permission = (typeof permissions)[number];

/** Matrice indicative — la vérification réelle se fera aussi via RLS Supabase et côté serveur. */
export const rolePermissions: Record<Role, readonly Permission[]> = {
  super_admin: permissions,
  direction_generale: [
    "dashboard:read",
    "programmes:read",
    "programmes:write",
    "projets:read",
    "projets:write",
    "activites:read",
    "beneficiaires:read",
    "indicateurs:read",
    "finances:read",
    "dons:read",
    "payments:read",
    "actualites:read",
    "actualites:write",
    "newsletter:read",
    "messages:read",
    "adhesions:read",
    "partenaires:read",
    "partenaires:write",
    "clusters:read",
    "urgences:read",
    "urgences:write",
    "clusters:read",
    "urgences:read",
    "urgences:write",
    "equipe:read",
    "statistiques:read",
    "rapports:read",
    "rapports:write",
    "rapports:export",
    "histoires:read",
    "histoires:write",
    "temoignages:write",
    "appels-offres:read",
    "appels-offres:write",
    "enquetes:read",
    "enquetes:write",
    "agents:read",
    "agents:write",
    "pages:write",
    "utilisateurs:read",
    "journal:read",
  ],
  secretariat: [
    "dashboard:read",
    "messages:read",
    "messages:write",
    "adhesions:read",
    "adhesions:write",
    "partenaires:read",
    "equipe:read",
    "actualites:read",
  ],
  charge_programmes: [
    "dashboard:read",
    "programmes:read",
    "programmes:write",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "indicateurs:write",
    "statistiques:read",
    "rapports:read",
    "rapports:write",
    "enquetes:read",
    "enquetes:write",
    "agents:read",
  ],
  coordination_urgences: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "rapports:read",
    "urgences:read",
    "urgences:write",
  ],
  coordination_sante: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "rapports:read",
  ],
  coordination_developpement: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "projets:write",
    "activites:read",
    "activites:write",
    "beneficiaires:read",
    "indicateurs:read",
    "rapports:read",
  ],
  coordination_meal: [
    "dashboard:read",
    "indicateurs:read",
    "indicateurs:write",
    "beneficiaires:read",
    "statistiques:read",
    "rapports:read",
    "rapports:write",
    "rapports:export",
  ],
  logistique: [
    "dashboard:read",
    "projets:read",
    "activites:read",
    "rapports:read",
  ],
  ressources_humaines: [
    "dashboard:read",
    "equipe:read",
    "equipe:write",
    "utilisateurs:read",
    "opportunites:read",
    "opportunites:write",
    "candidatures:read",
    "candidatures:write",
    "agents:read",
    "agents:write",
    "enquetes:read",
  ],
  finance: [
    "dashboard:read",
    "finances:read",
    "finances:write",
    "dons:read",
    "dons:write",
    "payments:read",
    "payments:manage",
    "rapports:read",
    "rapports:export",
  ],
  communication: [
    "dashboard:read",
    "actualites:read",
    "actualites:write",
    "mediatheque:read",
    "mediatheque:write",
    "newsletter:read",
    "newsletter:write",
    "newsletter:send",
    "messages:read",
    "documents:read",
    "documents:write",
  ],
  lecture_partenaire: [
    "dashboard:read",
    "programmes:read",
    "projets:read",
    "statistiques:read",
    "rapports:read",
  ],
};

export function roleHasPermission(role: Role, permission: Permission): boolean {
  return rolePermissions[role].includes(permission);
}
