export const roles = [
  "platform_owner",
  "platform_admin",
  "support_agent",
  "billing_admin",
  "tenant_owner",
  "tenant_super_admin",
  "super_admin",
  "admin_principal_direction",
  "admin_principal_it",
  "admin_principal",
  "administrateur",
  "admin_module",
  "responsable",
  "responsable_module",
  "direction_generale",
  "secretariat",
  "charge_programmes",
  "coordination_urgences",
  "coordination_sante",
  "coordination_developpement",
  "coordination_meal",
  "logistique",
  "ressources_humaines",
  "finance",
  "communication",
  "agent",
  "employe",
  "agent_terrain",
  "auditeur",
  "lecture_seule",
  "partenaire_lecture",
  "lecture_partenaire",
  "utilisateur_public",
] as const;

export type Role = (typeof roles)[number];

export const roleLabels: Record<Role, string> = {
  platform_owner: "Propriétaire plateforme",
  platform_admin: "Administrateur plateforme",
  support_agent: "Agent support AFD",
  billing_admin: "Administrateur facturation",
  tenant_owner: "Propriétaire organisation",
  tenant_super_admin: "Super administrateur organisation",
  super_admin: "Super administrateur",
  admin_principal_direction: "Administrateur principal — Direction",
  admin_principal_it: "Administratrice principale — IT",
  admin_principal: "Administrateur principal",
  administrateur: "Administrateur principal (legacy)",
  admin_module: "Administrateur de module",
  responsable: "Responsable",
  responsable_module: "Responsable de module",
  direction_generale: "Direction générale",
  secretariat: "Secrétariat",
  charge_programmes: "Chargé(e) de programmes",
  coordination_urgences: "Coordination urgences",
  coordination_sante: "Coordination santé",
  coordination_developpement: "Coordination développement",
  coordination_meal: "Coordination MEAL",
  logistique: "Logistique",
  ressources_humaines: "Ressources humaines",
  finance: "Finance",
  communication: "Communication",
  agent: "Agent",
  employe: "Employé",
  agent_terrain: "Agent terrain",
  auditeur: "Auditeur",
  lecture_seule: "Lecture seule",
  partenaire_lecture: "Partenaire (lecture)",
  lecture_partenaire: "Lecture partenaire",
  utilisateur_public: "Utilisateur public",
};
