import { requirePermission } from "@/lib/auth/require-permission";
import { getAdminApplications } from "@/lib/queries/admin/candidatures";
import { getSignedApplicationFileUrl, updateApplicationStatus } from "@/features/opportunites/actions/manage-application";

export default async function CandidaturesPage() {
  await requirePermission("candidatures:read");
  const items = await getAdminApplications();
  return <main className="space-y-6 p-6"><h1 className="text-2xl font-bold">Candidatures</h1><div className="overflow-x-auto rounded border bg-white"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">Candidat·e</th><th>E-mail</th><th>Origine</th><th>Dates</th><th>Traitement interne</th></tr></thead><tbody>{await Promise.all(items.map(async (item) => { const cvUrl = item.cv_storage_path ? await getSignedApplicationFileUrl(item.cv_storage_path) : null; return <tr className="border-t align-top" key={item.id}><td className="p-3">{item.prenom} {item.nom}</td><td>{item.email}</td><td>{item.est_spontanee ? "Spontanée" : "Opportunité"}</td><td className="p-3">{new Date(item.created_at).toLocaleDateString("fr-FR")}<br /><span className="text-xs text-gray-500">Mis à jour : {new Date(item.updated_at).toLocaleDateString("fr-FR")}</span></td><td className="p-3"><form action={updateApplicationStatus} className="grid min-w-64 gap-2"><input type="hidden" name="id" value={item.id} /><input name="statut" defaultValue={item.statut} className="rounded border p-2" aria-label={`Statut de ${item.prenom} ${item.nom}`} /><textarea name="note_interne" defaultValue={item.note_interne ?? ""} placeholder="Note interne" className="rounded border p-2" /><div className="flex gap-2"><button className="rounded bg-[var(--afd-blue)] px-3 py-2 text-white">Enregistrer</button>{cvUrl ? <a href={cvUrl} className="rounded border px-3 py-2 text-[var(--afd-blue)]">Télécharger le CV</a> : null}</div></form></td></tr>; }))}</tbody></table></div></main>;
}
